<?xml version="1.0" encoding="utf-8"?><Database Name="yt.gis" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\X;Initial Catalog=yt.gis;User ID=sa" SettingsObjectName="X.App.Properties.Settings" SettingsPropertyName="x_linkConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.x_block" Member="x_block">
    <Type Name="x_block">
      <Column Name="block_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[file]" Member="file" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="y" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="x_service_x_block" Member="x_service" ThisKey="service_id" OtherKey="service_id" Type="x_service" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.x_service" Member="x_service">
    <Type Name="x_service">
      <Column Name="service_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="dir" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="secret_key" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="docinfo" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="blocksize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="innerextend" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fullextend" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="watermark" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="cache" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="version" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="x_service_x_block" Member="x_block" ThisKey="service_id" OtherKey="service_id" Type="x_block" />
      <Association Name="x_service_x_grid" Member="x_grid" ThisKey="service_id" OtherKey="service_id" Type="x_grid" />
      <Association Name="x_service_x_layer" Member="x_layer" ThisKey="service_id" OtherKey="service_id" Type="x_layer" />
    </Type>
  </Table>
  <Table Name="dbo.x_dict" Member="x_dict">
    <Type Name="x_dict">
      <Column Name="dict_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="jp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="upval" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="value" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="f1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="f2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="f3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="f4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="f5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="f6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="f7" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="f8" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.x_grid" Member="x_grid">
    <Type Name="x_grid">
      <Column Name="grid_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="lng" Type="System.Decimal" DbType="Decimal(18,8)" CanBeNull="true" />
      <Column Name="lat" Type="System.Decimal" DbType="Decimal(18,8)" CanBeNull="true" />
      <Column Name="style" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="points" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="x_service_x_grid" Member="x_service" ThisKey="service_id" OtherKey="service_id" Type="x_service" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.x_layer" Member="x_layer">
    <Type Name="x_layer">
      <Column Name="layer_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[desc]" Member="desc" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="copy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="extend" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="show_field" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="id_field" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="fiedls" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="drawstyle" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="x_service_x_layer" Member="x_service" ThisKey="service_id" OtherKey="service_id" Type="x_service" IsForeignKey="true" />
    </Type>
  </Table>
</Database>